import * as THREE from 'three';
import type {GardenState,Act} from '../core/GardenState';
import {giftBudget,giftsUsed,saveState} from '../core/GardenState';
import type {Physics} from '../core/Physics';
import type {Input} from '../core/Input';
import type {Garden,Gate,MidObject} from '../world/Garden';
import {C} from '../world/Garden';
import type {PlayerRig} from '../player/PlayerRig';
import type {Particles} from '../feel/Particles';
import type {Sound} from '../feel/Sound';
import type {Juice} from '../feel/Juice';
import {ProjectileGame,type Shot} from './ProjectileGame';
import {Storm} from '../world/Storm';
import {TUNING} from '../tuning';

const lines:Record<number,string>={1:'Let the beauty we love be what we do.',2:'The wound is the place where light enters you.',3:'Maybe you are searching among the branches for what appears only in the roots.',4:'What you seek is seeking you.'};
export class Acts{
  projectile:ProjectileGame;storm:Storm;actTime=0;plantHold=0;plantTime=0;groundPlot?:THREE.Mesh;transitioning=false;onTransition?:(act:Act,line:string)=>void;onFinale?:()=>void;
  constructor(public state:GardenState,public garden:Garden,public rig:PlayerRig,public physics:Physics,public input:Input,public camera:THREE.Camera,public particles:Particles,public sound:Sound,public juice:Juice){this.projectile=new ProjectileGame(garden.scene,physics,input,camera,particles,sound);this.storm=new Storm(garden.scene,physics,rig,particles,sound);garden.scene.userData.middles=garden.middles;this.projectile.onLand=(shot,point)=>this.land(shot,point);this.rig.onBurst=()=>this.burst();this.storm.onPass=()=>{if(this.state.act===1)this.state.act1.stormsSurvived++;if(this.state.act===3&&!this.state.act3.plant)this.state.act3.stormDamage++;saveState(this.state)};this.enter(this.state.act,false)}
  enter(act:Act,announce=true){this.state.act=act;this.actTime=0;this.transitioning=false;if(act==='finale'){saveState(this.state);this.onFinale?.();return}this.garden.unlock(act);if(act===1)this.rig.setPosition(-50,-50);if(act===2){this.rig.setPosition(9,-48);this.rig.setAnchor(true);this.projectile.setOrigin(9,-48)}if(act===3){this.rig.setAnchor(false);this.rig.tetherBarbell();this.rig.setPosition(-51,14);this.pickHollows()}if(act===4){this.rig.setAnchor(true);this.rig.setPosition(9,10);this.projectile.setOrigin(9,10)}saveState(this.state);if(announce)this.onTransition?.(act,lines[act])}
  next(){if(this.transitioning||this.state.act==='finale')return;this.transitioning=true;const next:Act=this.state.act===4?'finale':(Number(this.state.act)+1) as Act;setTimeout(()=>this.enter(next),1150)}
  fixedUpdate(dt:number){if(this.state.act==='finale')return;this.actTime+=dt;if(this.state.act===1)this.act1(dt);if(this.state.act===2)this.act2(dt);if(this.state.act===3)this.act3(dt);if(this.state.act===4)this.act4(dt)}
  act1(dt:number){this.rig.fixedUpdate(dt);this.storm.fixedUpdate(dt,1);if(this.input.actionPressed){const p=this.rig.playerBody.translation(),middle=this.garden.middles.find(m=>!m.shattered&&Math.hypot(m.body.translation().x-p.x,m.body.translation().z-p.z)<2.7);if(middle&&this.rig.currentTether===this.rig.rodBody)this.rig.tetherTo(middle.body);else if(this.rig.currentTether!==this.rig.rodBody)this.rig.tetherBarbell()}const p=this.rig.playerBody.translation();if(p.x>-12&&p.z>-12&&this.state.act1.gatesBroken.length===3&&this.rig.currentTether===this.rig.rodBody)this.next()}
  contact(force:number,a:{userData?:unknown},b:{userData?:unknown}){const ua=a.userData as {role?:string;id?:string}|undefined,ub=b.userData as {role?:string;id?:string}|undefined;if(force>5){this.juice.shake(force);this.sound.impact(Math.min(9,force*.08))}if(this.state.act===1){const gateRole=ua?.role==='gate'?ua:ub?.role==='gate'?ub:null,heavy=ua?.role==='heavy'||ub?.role==='heavy';if(gateRole&&heavy&&force>TUNING.smashThreshold)this.breakGate(gateRole.id!);const middleRole=ua?.role==='middle'?ua:ub?.role==='middle'?ub:null;if(middleRole&&force>34)this.shatter(middleRole.id!)}if(this.state.act===4){this.projectile.markBounce(a as never);this.projectile.markBounce(b as never)}}
  breakGate(id:string){const gate=this.garden.gates.find(item=>item.id===id);if(!gate||gate.broken)return;gate.broken=true;gate.mesh.visible=false;gate.body.setEnabled(false);this.state.act1.gatesBroken.push(id);this.garden.rubble(gate.mesh.position);this.particles.emit(gate.mesh.position.clone().setY(1),C.lapis,55,9,7);this.juice.freeze(5);this.juice.shake(80);this.sound.crack();saveState(this.state)}
  shatter(id:string){const middle=this.garden.middles.find(item=>item.id===id);if(!middle||middle.shattered)return;middle.shattered=true;middle.mesh.visible=false;middle.body.setEnabled(false);this.state.act1.shattered.push(id);const p=middle.body.translation();this.particles.emit(new THREE.Vector3(p.x,p.y,p.z),C.vermilion,32,7,5);this.sound.crack();if(this.rig.currentTether===middle.body)this.rig.tetherBarbell();saveState(this.state)}
  burst(){if(this.state.act!==1)return;const p=this.rig.playerBody.translation();if(Math.abs(p.z+29)<5){this.state.act1.burstsRidden++;this.juice.shake(24);saveState(this.state)}}
  act2(dt:number){const energy=140+this.state.act1.gatesBroken.length*34+this.state.act1.stormsSurvived*12+this.state.act1.burstsRidden*10;this.projectile.fixedUpdate(dt,'energy',this.state.act2.waste<energy);if(this.state.act2.waste>=energy&&this.projectile.shots.length===0)this.next()}
  land(shot:Shot,point:THREE.Vector3){if(shot.kind==='energy'&&this.state.act===2){let structure=this.garden.structures.find(item=>point.distanceTo(item.position)<6.5);this.state.act2.waste+=34;if(structure){structure.fill=Math.min(100,structure.fill+34);this.state.act2.poured[structure.id]=structure.fill;structure.mesh.visible=true;structure.mesh.scale.y=Math.max(.04,structure.fill/100);if(structure.fill>=96&&!this.state.act2.built.includes(structure.id)){this.state.act2.built.push(structure.id);this.sound.bloom()}this.particles.emit(structure.position.clone().setY(2),C.gold,35,6,5)}else{this.state.act2.stains.push({x:point.x,z:point.z,size:1.1});this.garden.stain(point.x,point.z,1.1);this.particles.emit(point,C.gold,18,4,2)}saveState(this.state)}else if(shot.kind==='gift'&&this.state.act===4)this.giftLand(shot,point)}
  pickHollows(){if(this.state.act3.hollow.length)return;const ids=this.garden.plots.map(plot=>plot.userData.id as string).sort(()=>Math.random()-.5);this.state.act3.hollow=ids.slice(0,2);saveState(this.state)}
  act3(dt:number){this.rig.fixedUpdate(dt);this.state.act3.time+=dt;const dusk=Math.max(0,(this.state.act3.time-150)/90);this.storm.fixedUpdate(dt,3,dusk*35);const p=this.rig.playerBody.translation();if(this.actTime%1<dt){this.state.act3.path.push({x:p.x,z:p.z});if(this.state.act3.path.length>250)this.state.act3.path.shift()}const plot=this.garden.plots.find(item=>Math.hypot(item.position.x-p.x,item.position.z-p.z)<3.6);if(this.input.actionPressed&&plot&&!this.state.act3.plant){this.groundPlot=plot;this.plantHold=0}if(this.input.actionDown&&this.groundPlot&&!this.state.act3.plant){this.plantHold+=dt;if(this.plantHold>1.5)this.plant(this.groundPlot)}if(this.input.actionReleased&&this.groundPlot&&!this.state.act3.plant){if(this.plantHold<.7)this.test(this.groundPlot);this.groundPlot=undefined;this.plantHold=0}if(this.state.act3.plant&&this.actTime-this.plantTime>10)this.next()}
  test(plot:THREE.Mesh){const id=plot.userData.id as string;if(this.state.act3.tested.includes(id))return;this.state.act3.tested.push(id);const hollow=this.state.act3.hollow.includes(id);if(hollow){this.state.act3.cracks.push({x:plot.position.x,z:plot.position.z});this.garden.crack(plot.position.x,plot.position.z);this.particles.emit(plot.position.clone().setY(.5),C.ink,38,6,5);this.sound.crack();this.juice.freeze(4)}else{const ring=plot.clone();ring.scale.setScalar(.2);ring.material=(plot.material as THREE.Material).clone();this.garden.traces.add(ring);let n=0;const grow=setInterval(()=>{ring.scale.setScalar(.2+n*.13);((ring.material as THREE.MeshBasicMaterial)).opacity=.7-n*.05;if(++n>12){clearInterval(grow);ring.removeFromParent()}},35);this.sound.chime(2)}saveState(this.state)}
  plant(plot:THREE.Mesh){const id=plot.userData.id as string,untested=!this.state.act3.tested.includes(id),hollow=this.state.act3.hollow.includes(id),tilted=untested&&hollow,lush=this.state.act3.stormDamage<2&&!tilted;this.state.act3.plant={x:plot.position.x,z:plot.position.z,tilted,lush};this.plantTime=this.actTime;this.groundPlot=undefined;this.garden.plantTree(plot.position.x,plot.position.z,tilted,lush);this.particles.emit(plot.position.clone().setY(1),C.gold,80,10,8);this.sound.bloom();this.juice.freeze(5);saveState(this.state)}
  act4(dt:number){const remaining=giftBudget(this.state)-giftsUsed(this.state);this.projectile.fixedUpdate(dt,'gift',remaining>0);if(remaining<=0&&this.projectile.shots.length===0)this.next()}
  giftLand(shot:Shot,point:THREE.Vector3){let nearest:[string,THREE.Group]|undefined,distance=Infinity;for(const entry of this.garden.figures){const d=point.distanceTo(entry[1].position);if(d<distance){nearest=entry;distance=d}}if(nearest&&distance<5.5){const [id,figure]=nearest;this.state.act4.gifts[id]=(this.state.act4.gifts[id]||0)+1;const count=shot.bounced?18:8;for(let i=0;i<count;i++)this.garden.flower(figure.position.x+(Math.random()-.5)*(shot.bounced?7:4),figure.position.z+(Math.random()-.5)*(shot.bounced?7:4),shot.bounced?1.3:.9);if(shot.bounced){this.state.act4.bankShots++;figure.scale.setScalar(1.18)}this.sound.bloom();this.particles.emit(figure.position.clone().setY(2),C.gold,shot.bounced?70:35,8,7)}else{this.state.act4.wildflowers.push({x:point.x,z:point.z});this.garden.flower(point.x,point.z,.75);this.sound.chime(1)}saveState(this.state)}
  renderUpdate(){this.storm.renderUpdate()}
}
