import * as THREE from 'three';
import {Physics,RAPIER} from '../core/Physics';
import type {GardenState} from '../core/GardenState';

export const C={lapis:0x1f3a93,turquoise:0x40c4b7,saffron:0xf4a300,gold:0xd4af37,vermilion:0xc0392b,paper:0xf5edd8,ink:0x1a1a22,green:0x2e7d4f,grey:0x77736b};
const toon=(color:number)=>new THREE.MeshToonMaterial({color});
const basic=(color:number,options:THREE.MeshBasicMaterialParameters={})=>new THREE.MeshBasicMaterial({color,...options});
const box=(w:number,h:number,d:number,color:number)=>new THREE.Mesh(new THREE.BoxGeometry(w,h,d),toon(color));

function treeGeometry(){const group=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.14,.24,2.7,6),toon(0x6b4b2e));trunk.position.y=1.35;group.add(trunk);for(let i=0;i<3;i++){const crown=new THREE.Mesh(new THREE.ConeGeometry(1.1-i*.14,2.8,8),toon(C.green));crown.position.y=2.6+i*.65;group.add(crown)}return group}
export function makeFigure(color:number){const group=new THREE.Group();const robe=new THREE.Mesh(new THREE.ConeGeometry(.68,1.7,8),toon(color));robe.position.y=.85;group.add(robe);const head=new THREE.Mesh(new THREE.SphereGeometry(.32,9,6),toon(0xc98f68));head.position.y=1.95;group.add(head);const turban=new THREE.Mesh(new THREE.TorusGeometry(.29,.085,5,12),toon(C.paper));turban.rotation.x=Math.PI/2;turban.position.y=2.08;group.add(turban);return group}
function makeStructure(id:string){const group=new THREE.Group();if(id==='pavilion'){group.add(box(7,.4,6,C.paper));for(const x of [-2.5,2.5])for(const z of [-2,2]){const column=new THREE.Mesh(new THREE.CylinderGeometry(.22,.28,4,8),toon(C.paper));column.position.set(x,2.2,z);group.add(column)}const roof=new THREE.Mesh(new THREE.ConeGeometry(5,2.2,8),toon(C.lapis));roof.position.y=5.1;group.add(roof)}else if(id==='orchard'){for(let x=-3;x<=3;x+=2)for(let z=-2;z<=2;z+=2){const tree=treeGeometry();tree.scale.setScalar(.7);tree.position.set(x,0,z);group.add(tree)}}else if(id==='library'){group.add(box(7,4.8,1,C.paper));for(const x of [-2.2,0,2.2]){const arch=new THREE.Mesh(new THREE.TorusGeometry(.65,.15,7,14,Math.PI),toon(C.lapis));arch.position.set(x,2.1,.58);group.add(arch)}}else{const tower=new THREE.Mesh(new THREE.CylinderGeometry(2.1,2.7,7,8),toon(C.paper));tower.position.y=3.5;group.add(tower);const crown=new THREE.Mesh(new THREE.ConeGeometry(3.1,2,8),toon(C.gold));crown.position.y=8;group.add(crown)}return group}

export type Gate={id:string;mesh:THREE.Group;body:RAPIER.RigidBody;collider:RAPIER.Collider;broken:boolean};
export type MidObject={id:string;mesh:THREE.Object3D;body:RAPIER.RigidBody;collider:RAPIER.Collider;shattered:boolean};
export type Structure={id:string;mesh:THREE.Group;position:THREE.Vector3;fill:number};

export class Garden{
  root=new THREE.Group();traces=new THREE.Group();quadrants:THREE.Group[]=[];grounds:THREE.Mesh[]=[];gates:Gate[]=[];middles:MidObject[]=[];structures:Structure[]=[];plots:THREE.Mesh[]=[];figures=new Map<string,THREE.Group>();waterMaterials:THREE.ShaderMaterial[]=[];goldMaterial:THREE.ShaderMaterial;gap!:THREE.Mesh;
  constructor(public scene:THREE.Scene,public physics:Physics,public state:GardenState){
    scene.add(this.root);this.root.add(this.traces);this.goldMaterial=this.makeGold();this.buildGround();this.buildAct1();this.buildStructures();this.buildPlots();this.buildFigures();this.restoreTraces();
  }
  makeGold(){return new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uColor:{value:new THREE.Color(C.gold)}},vertexShader:`varying vec3 vN;varying vec3 vP;void main(){vN=normalize(normalMatrix*normal);vP=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float uTime;uniform vec3 uColor;varying vec3 vN;varying vec3 vP;void main(){float edge=pow(max(dot(normalize(vN),normalize(vec3(.3,.8,.5))),0.),3.);float spark=.82+.18*sin(uTime*4.+vP.y*11.+vP.x*3.);gl_FragColor=vec4(uColor*(.72+edge*.65)*spark,1.);}`})}
  waterMaterial(){const material=new THREE.ShaderMaterial({uniforms:{uTime:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float uTime;varying vec2 vUv;void main(){float r=sin((vUv.x+vUv.y)*48.-uTime*2.)*.06;gl_FragColor=vec4(mix(vec3(.08,.46,.58),vec3(.25,.77,.72),vUv.y+r),.95);}`});this.waterMaterials.push(material);return material}
  buildGround(){const centers=[[-30,-30],[30,-30],[-30,30],[30,30]],colors=[C.lapis,C.saffron,C.green,C.vermilion];centers.forEach(([x,z],index)=>{const group=new THREE.Group();group.position.set(x,0,z);this.root.add(group);this.quadrants.push(group);const ground=box(52,1.2,52,index+1<=Number(this.state.act)||this.state.act==='finale'?colors[index]:C.grey);ground.position.y=-.7;ground.userData={color:colors[index]};group.add(ground);this.grounds.push(ground);const terrace=box(44,.32,44,C.paper);terrace.position.y=.06;group.add(terrace);this.physics.fixedBox(x,-.7,z,26,.6,26,{role:'ground'});for(let i=0;i<16;i++){const tree=treeGeometry();const edge=i%4,step=(i%4-1.5)*11;tree.position.set(edge<2?step:edge===2?-21:21,0,edge<2?(edge?21:-21):step);tree.scale.setScalar(.85+(i%3)*.08);group.add(tree)}});const mx=new THREE.Mesh(new THREE.PlaneGeometry(120,7),this.waterMaterial()),mz=new THREE.Mesh(new THREE.PlaneGeometry(120,7),this.waterMaterial());mx.rotation.x=mz.rotation.x=-Math.PI/2;mz.rotation.z=Math.PI/2;mx.position.y=mz.position.y=.12;this.root.add(mx,mz);const rim=new THREE.Mesh(new THREE.CylinderGeometry(8.2,8.2,.35,8),toon(C.gold));rim.position.y=.15;const pool=new THREE.Mesh(new THREE.CylinderGeometry(7.5,7.5,.42,8),toon(C.turquoise));pool.position.y=.38;this.root.add(rim,pool)}
  buildAct1(){
    this.gap=box(42,.08,6,C.ink);this.gap.position.set(-31,.25,-29);this.root.add(this.gap);
    const gateData=[['gate-a',-30,-45,0],['gate-b',-45,-18,Math.PI/2],['gate-c',-17,-12,0]] as const;
    gateData.forEach(([id,x,z,rotation])=>{const mesh=new THREE.Group();for(let i=-2;i<=2;i++){const post=box(1,4.5,1,C.lapis);post.position.set(i*1.15,2.25,0);mesh.add(post)}mesh.position.set(x,0,z);mesh.rotation.y=rotation;this.root.add(mesh);const body=this.physics.world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(x,2.25,z).setRotation({x:0,y:Math.sin(rotation/2),z:0,w:Math.cos(rotation/2)}));const collider=this.physics.world.createCollider(RAPIER.ColliderDesc.cuboid(3.2,2.25,.55).setActiveEvents(RAPIER.ActiveEvents.CONTACT_FORCE_EVENTS).setContactForceEventThreshold(18),body);collider.userData={role:'gate',id};const gate={id,mesh,body,collider,broken:this.state.act1.gatesBroken.includes(id)};if(gate.broken){mesh.visible=false;body.setEnabled(false)}this.gates.push(gate)});
    for(let i=0;i<7;i++){const id=`middle-${i}`,mesh=i%2?box(1.6,1.7,1.6,[C.turquoise,C.saffron,C.vermilion][i%3]):new THREE.Mesh(new THREE.CylinderGeometry(.7,.9,1.8,8),toon([C.saffron,C.turquoise,C.lapis][i%3]));mesh.position.set(-49+(i%4)*10,1.1,-50+Math.floor(i/4)*15);this.root.add(mesh);const body=this.physics.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(mesh.position.x,1.1,mesh.position.z).setLinearDamping(.8));const collider=this.physics.world.createCollider(RAPIER.ColliderDesc.cuboid(.75,.85,.75).setMass(3.4).setActiveEvents(RAPIER.ActiveEvents.CONTACT_FORCE_EVENTS).setContactForceEventThreshold(15),body);collider.userData={role:'middle',id};this.physics.add(body,mesh);const middle={id,mesh,body,collider,shattered:this.state.act1.shattered.includes(id)};if(middle.shattered){mesh.visible=false;body.setEnabled(false)}this.middles.push(middle)}
  }
  buildStructures(){const data=[['pavilion',17,-43],['orchard',43,-42],['library',17,-18],['watchtower',43,-18]] as const;data.forEach(([id,x,z])=>{const slab=box(11,.45,9,0xa6987c);slab.position.set(x,.3,z);this.root.add(slab);const mesh=makeStructure(id);mesh.position.set(x,.55,z);const fill=this.state.act2.poured[id]||0;mesh.scale.y=Math.max(.02,fill/100);mesh.visible=fill>0;this.root.add(mesh);this.structures.push({id,mesh,position:new THREE.Vector3(x,.5,z),fill});this.physics.fixedBox(x,2.5,z,4,2.5,3,{role:'structure',id})})}
  buildPlots(){const coords=[[-47,17],[-29,17],[-14,20],[-45,43],[-28,44],[-14,40]];coords.forEach(([x,z],index)=>{const ring=new THREE.Mesh(new THREE.RingGeometry(2.4,3.1,32),basic(index%2?C.gold:C.turquoise,{transparent:true,opacity:.65,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.2,z);ring.userData={id:`plot-${index}`,x,z};this.root.add(ring);this.plots.push(ring)})}
  buildFigures(){const colors={saffron:C.saffron,lapis:C.lapis,turquoise:C.turquoise,vermilion:C.vermilion};Object.entries(colors).forEach(([id,color],index)=>{const angle=index*Math.PI/2+.4,figure=makeFigure(color);figure.scale.y=.82;figure.position.set(30+Math.cos(angle)*14,0,30+Math.sin(angle)*14);figure.userData={id};this.figures.set(id,figure);this.root.add(figure)})}
  unlock(act:number){const ground=this.grounds[act-1];ground.material=(ground.material as THREE.Material).clone();(ground.material as THREE.MeshToonMaterial).color.setHex(ground.userData.color);this.quadrants[act-1].traverse(object=>{const mesh=object as THREE.Mesh;if(mesh.material&&mesh!==ground&&(mesh.material as THREE.MeshToonMaterial).color?.getHex()===C.grey)(mesh.material as THREE.MeshToonMaterial).color.setHex(C.green)})}
  rubble(position:THREE.Vector3,color=C.lapis,count=12){for(let i=0;i<count;i++){const shard=box(.25+Math.random()*.5,.12,.3+Math.random()*.6,color);shard.position.set(position.x+(Math.random()-.5)*4,.18,position.z+(Math.random()-.5)*3);shard.rotation.y=Math.random()*Math.PI;this.traces.add(shard)}}
  stain(x:number,z:number,size=1){const stain=new THREE.Mesh(new THREE.CircleGeometry(size,18),basic(C.gold,{transparent:true,opacity:.6,side:THREE.DoubleSide}));stain.rotation.x=-Math.PI/2;stain.position.set(x,.19,z);this.traces.add(stain)}
  flower(x:number,z:number,scale=1){const flower=new THREE.Group();for(let i=0;i<5;i++){const petal=new THREE.Mesh(new THREE.SphereGeometry(.18*scale,5,4),basic([C.saffron,C.turquoise,C.vermilion,C.gold][i%4]));petal.scale.set(1,.25,.6);petal.position.set(Math.cos(i*1.257)*.18,.3,Math.sin(i*1.257)*.18);flower.add(petal)}flower.position.set(x,0,z);this.traces.add(flower)}
  restoreTraces(){this.state.act1.gatesBroken.forEach((id,index)=>this.rubble(new THREE.Vector3(-40+index*11,0,-15),C.lapis));this.state.act2.stains.forEach(stain=>this.stain(stain.x,stain.z,stain.size));this.state.act3.cracks.forEach(crack=>this.crack(crack.x,crack.z));this.state.act4.wildflowers.forEach(point=>this.flower(point.x,point.z,.75));if(this.state.act3.plant)this.plantTree(this.state.act3.plant.x,this.state.act3.plant.z,this.state.act3.plant.tilted,this.state.act3.plant.lush)}
  crack(x:number,z:number){for(let i=0;i<8;i++){const line=new THREE.Mesh(new THREE.BoxGeometry(.08,.025,2+i*.25),basic(C.ink));line.position.set(x+Math.sin(i*2.1)*.8,.2,z+Math.cos(i*1.7)*.8);line.rotation.y=i*.78;this.traces.add(line)}}
  plantTree(x:number,z:number,tilted=false,lush=true){const tree=treeGeometry();tree.position.set(x,0,z);tree.scale.set(lush?1.7:1.2,lush?2:1.45,lush?1.7:1.2);if(tilted)tree.rotation.z=.28;tree.userData.tree=true;this.traces.add(tree);for(let i=0;i<10;i++){const angle=i*.628,line=new THREE.Mesh(new THREE.BoxGeometry(.06,.025,5+(i%3)*1.2),basic(C.gold));line.position.set(x+Math.sin(angle)*2.2,.21,z+Math.cos(angle)*2.2);line.rotation.y=angle;this.traces.add(line)}return tree}
  update(time:number){this.goldMaterial.uniforms.uTime.value=time;this.waterMaterials.forEach(material=>material.uniforms.uTime.value=time)}
}

export {box,toon,basic};
