import * as THREE from 'three';
import {Physics,RAPIER} from '../core/Physics';
import {Input} from '../core/Input';
import {Particles} from '../feel/Particles';
import {Sound} from '../feel/Sound';
import {TUNING} from '../tuning';
import {C,toon,basic} from '../world/Garden';

export class PlayerRig{
  group=new THREE.Group();figure=new THREE.Group();barbell=new THREE.Group();rope:THREE.Line;playerBody:RAPIER.RigidBody;playerCollider:RAPIER.Collider;controller:RAPIER.KinematicCharacterController;rodBody:RAPIER.RigidBody;heavyBody:RAPIER.RigidBody;volatileBody:RAPIER.RigidBody;rodCollider:RAPIER.Collider;heavyCollider:RAPIER.Collider;volatileCollider:RAPIER.Collider;tether:RAPIER.ImpulseJoint;currentTether:RAPIER.RigidBody;burstIn=5;telegraph=0;anchored=false;lastMove=new THREE.Vector2();tmp3=new THREE.Vector3();onBurst?:()=>void;
  constructor(public scene:THREE.Scene,public physics:Physics,public input:Input,public particles:Particles,public sound:Sound,gold:THREE.Material){
    scene.add(this.group);this.figure=this.makeFigure();scene.add(this.figure);
    this.playerBody=physics.world.createRigidBody(RAPIER.RigidBodyDesc.kinematicPositionBased().setTranslation(-50,1.15,-50));this.playerCollider=physics.world.createCollider(RAPIER.ColliderDesc.capsule(.65,.5).setFriction(.8),this.playerBody);this.playerCollider.userData={role:'player'};physics.add(this.playerBody,this.figure);
    this.controller=physics.world.createCharacterController(.06);this.controller.enableAutostep(.45,.3,true);this.controller.enableSnapToGround(.35);this.controller.setApplyImpulsesToDynamicBodies(true);this.controller.setCharacterMass(4);
    const identity={x:0,y:0,z:0,w:1};
    this.rodBody=physics.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(-48,1.25,-46).setLinearDamping(.45).setAngularDamping(.7));this.rodCollider=physics.world.createCollider(RAPIER.ColliderDesc.cuboid(3,.17,.17).setMass(TUNING.rodMass).setFriction(.85).setActiveEvents(RAPIER.ActiveEvents.CONTACT_FORCE_EVENTS).setContactForceEventThreshold(8),this.rodBody);this.rodCollider.userData={role:'rod'};
    this.heavyBody=physics.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(-51,1.25,-46).setLinearDamping(TUNING.heavyDamping).setCcdEnabled(true));this.heavyCollider=physics.world.createCollider(RAPIER.ColliderDesc.ball(1.15).setMass(TUNING.heavyMass).setFriction(1.2).setRestitution(.08).setActiveEvents(RAPIER.ActiveEvents.CONTACT_FORCE_EVENTS).setContactForceEventThreshold(8),this.heavyBody);this.heavyCollider.userData={role:'heavy'};
    this.volatileBody=physics.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(-45,1.25,-46).setLinearDamping(TUNING.volatileDamping).setCcdEnabled(true));this.volatileCollider=physics.world.createCollider(RAPIER.ColliderDesc.ball(1).setMass(TUNING.volatileMass).setFriction(.45).setRestitution(.35).setActiveEvents(RAPIER.ActiveEvents.CONTACT_FORCE_EVENTS).setContactForceEventThreshold(6),this.volatileBody);this.volatileCollider.userData={role:'volatile'};
    const rodMesh=new THREE.Mesh(new THREE.BoxGeometry(6,.34,.34),toon(C.gold)),heavyMesh=new THREE.Mesh(new THREE.DodecahedronGeometry(1.15,1),toon(0x3e393b)),volatileMesh=new THREE.Mesh(new THREE.IcosahedronGeometry(1,2),gold);this.barbell.add(rodMesh,heavyMesh,volatileMesh);scene.add(this.barbell);physics.add(this.rodBody,rodMesh);physics.add(this.heavyBody,heavyMesh);physics.add(this.volatileBody,volatileMesh);volatileMesh.userData.volatile=true;heavyMesh.userData.heavy=true;
    physics.world.createImpulseJoint(RAPIER.JointData.fixed({x:-3,y:0,z:0},identity,{x:0,y:0,z:0},identity),this.rodBody,this.heavyBody,true);physics.world.createImpulseJoint(RAPIER.JointData.fixed({x:3,y:0,z:0},identity,{x:0,y:0,z:0},identity),this.rodBody,this.volatileBody,true);
    this.currentTether=this.rodBody;this.tether=this.makeTether(this.rodBody);
    const ropeGeometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]);this.rope=new THREE.Line(ropeGeometry,new THREE.LineBasicMaterial({color:C.gold}));scene.add(this.rope);
  }
  makeFigure(){const figure=new THREE.Group();const robe=new THREE.Mesh(new THREE.ConeGeometry(.72,1.9,8),toon(C.lapis));robe.position.y=.95;figure.add(robe);const sash=new THREE.Mesh(new THREE.TorusGeometry(.52,.08,5,12),toon(C.gold));sash.rotation.x=Math.PI/2;sash.position.y=1.3;figure.add(sash);const head=new THREE.Mesh(new THREE.SphereGeometry(.34,9,6),toon(0xc98f68));head.position.y=2.2;figure.add(head);const shadow=new THREE.Mesh(new THREE.CircleGeometry(.7,20),basic(C.ink,{transparent:true,opacity:.24,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-1.1;figure.add(shadow);return figure}
  makeTether(body:RAPIER.RigidBody){return this.physics.world.createImpulseJoint(RAPIER.JointData.spring(TUNING.ropeRest,TUNING.ropeStiffness,TUNING.ropeDamping,{x:0,y:0,z:0},{x:0,y:0,z:0}),this.playerBody,body,true)}
  tetherTo(body:RAPIER.RigidBody){this.physics.world.removeImpulseJoint(this.tether,true);this.currentTether=body;this.tether=this.makeTether(body);this.sound.chime(1)}
  tetherBarbell(){if(this.currentTether!==this.rodBody)this.tetherTo(this.rodBody)}
  setPosition(x:number,z:number){this.playerBody.setTranslation({x,y:1.15,z},true);this.playerBody.setNextKinematicTranslation({x,y:1.15,z});this.rodBody.setTranslation({x:x+2,y:1.25,z:z+3},true);this.heavyBody.setTranslation({x:x-1,y:1.25,z:z+3},true);this.volatileBody.setTranslation({x:x+5,y:1.25,z:z+3},true);[this.rodBody,this.heavyBody,this.volatileBody].forEach(body=>body.setLinvel({x:0,y:0,z:0},true))}
  fixedUpdate(dt:number){
    const move=this.input.readMovement();this.lastMove.copy(move);const desired={x:move.x*TUNING.walkSpeed*dt,y:-.12,z:move.y*TUNING.walkSpeed*dt};this.controller.computeColliderMovement(this.playerCollider,desired);const result=this.controller.computedMovement(),p=this.playerBody.translation();this.playerBody.setNextKinematicTranslation({x:p.x+result.x,y:p.y+result.y,z:p.z+result.z});
    if(move.lengthSq()>.02){this.figure.rotation.y=Math.atan2(move.x,move.y);if(this.input.actionDown&&!this.anchored){const bp=this.rodBody.translation(),dx=bp.x-p.x,dz=bp.z-p.z,length=Math.max(.1,Math.hypot(dx,dz)),direction=Math.sign(move.x*dz-move.y*dx)||1;this.heavyBody.applyImpulse({x:-dz/length*TUNING.swingImpulse*direction,y:0,z:dx/length*TUNING.swingImpulse*direction},true)}}
    if(this.input.actionPressed&&move.lengthSq()<.05&&this.currentTether===this.rodBody)this.setAnchor(true);if(this.input.actionReleased&&this.anchored)this.setAnchor(false);
    this.burstIn-=dt;if(this.burstIn<.5&&this.telegraph<=0)this.telegraph=.5;if(this.telegraph>0){this.telegraph-=dt;this.sound.telegraph(1-this.telegraph/.5);if(this.telegraph<=0)this.burst()}
  }
  setAnchor(value:boolean){this.anchored=value;const type=value?RAPIER.RigidBodyType.Fixed:RAPIER.RigidBodyType.Dynamic;[this.rodBody,this.heavyBody,this.volatileBody].forEach(body=>body.setBodyType(type,true));if(value){const p=this.heavyBody.translation();this.particles.emit(new THREE.Vector3(p.x,.2,p.z),0x8e7050,22,4,3);this.sound.impact(TUNING.heavyMass)}}
  burst(){const angle=Math.random()*Math.PI*2,impulse={x:Math.cos(angle)*TUNING.burstImpulse,y:2,z:Math.sin(angle)*TUNING.burstImpulse};this.volatileBody.applyImpulse(impulse,true);const p=this.volatileBody.translation();this.particles.emit(new THREE.Vector3(p.x,p.y,p.z),C.gold,34,8,5);this.sound.whoosh();this.burstIn=TUNING.burstMin+Math.random()*(TUNING.burstMax-TUNING.burstMin);this.telegraph=0;this.onBurst?.()}
  renderUpdate(time:number){const player=this.figure.position,target=this.currentTether.translation(),array=(this.rope.geometry.getAttribute('position') as THREE.BufferAttribute).array as Float32Array;array[0]=player.x;array[1]=player.y+1;array[2]=player.z;array[3]=target.x;array[4]=target.y;array[5]=target.z;(this.rope.geometry.getAttribute('position') as THREE.BufferAttribute).needsUpdate=true;const volatile=this.barbell.children.find(child=>child.userData.volatile);if(volatile){const pulse=this.telegraph>0?1.15+(1-this.telegraph/.5)*.3:1+Math.sin(time*4)*.04;volatile.scale.setScalar(pulse)}const heavy=this.heavyBody.translation(),speed=this.heavyBody.linvel();if(Math.hypot(speed.x,speed.z)>.6&&heavy.y<1.35)this.particles.emit(new THREE.Vector3(heavy.x,.2,heavy.z),0x9f7d52,1,1,.5)}
}
